services:
  - type: web
    name: strike-feedback-api
    env: node
    region: oregon
    plan: free
    rootDir: api
    buildCommand: npm ci && npm run build
    startCommand: npx prisma generate && npx prisma migrate deploy && npx prisma db seed && npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: strike-feedback-db
          property: connectionString
      - key: FRONTEND_URL
        value: https://strike-feedback.vercel.app

databases:
  - name: strike-feedback-db
    databaseName: strike_feedback
    user: strike_user
    region: oregon
    plan: free
